canadaHouse/urls.py
from django.contrib import admin
from django.urls import path , include

import gopal

urlpatterns = [
    path('admin/', admin.site.urls),
    path('houses/', include('gopal.urls')),
    path('',gopal.views.home)
]

gopal/urls.py
from django.contrib import admin
from django.urls import path, include
from gopal.views import *

app_name = 'gopal'

urlpatterns = [
    path('', home, name='home'),
    path('list', list, name='list'),
    path('estimate', estimate, name='estimate'),
    path('R<int:house_id>', house_view, name='house_view')
]

gopal/models.py
from django.db import models

# data type hierarchy sample:
# to check a sample with if of : <id> --> https://gopalsharma.ca/listing/R<id>/
objectSample = {'mlsListingID': 'R2396512',
       'address': '# 4301 1289 Hornby Street, Vancouver, BC',
       'city': 'Vancouver',
       'community': 'Downtown VW',
       'state': 'BC',
       'ownership': 'Freehold Strata',
       'publicRemarks': "Great opportunity to own a dream home in a timeless architectural gem - ONE BURRARD PLACE. Located in the heart of downtown Vancouver. This functional two bedrooms with flex space above 43 floor features with finest fixtures & finishes including lofty 9' ceilings, floor to ceiling glazed windows, wide plank hardwood flooring throughout, motion sensor lighting in closets, central A/C, automated smart home controls & list go on. Building with five star amenities including full length lap pool, sauna, steam rooms, fitness center, 30,000 sq.ft of private clubhouse, secured floor-by-floor fob controlled, 24/7 butler concierge services. Mins walk to skytrain, Yaletown, shopping, restaurants. Enjoy City skyline and English Bay day & night. Truly a glamorous & luxurious living!",
       'price': 1380000,
       'bedrooms': 2,
       'baths': 2,
       'dateListed': '2019-08-13 07:00:00',
        'media': ['abe42153f7e2ca693da4d6388d640cde427cbb47.jpg', 'f53cb3ec6e4fa4cbda81c159d5747f510895bf98.jpg', 'aad98da13c7c90d1f9da0d5a8de029c5185657c5.jpg', 'bf5136f25f8e8a770fdaccff957e6c6c89d1325c.jpg', '371ddc31cb580877e2ff495f1a398c9ef9f11a72.jpg', 'd2f8109e5cd58c8d9b3d2d3c56fa1ae36e252488.jpg', 'bd4da0d19e4a42d8bf6beb069e36c6d0e574cef2.jpg', '945b3660227453b29ae42b75a3cc92b7950d1c4f.jpg', '807f454d98bd4a322b76732241b1f056b78bf530.jpg', 'ea18e06c6a87254fcedaf2d3cba59cef9be7b00d.jpg', '11fa844267b9576304b037df64d91a6ccbaac0aa.jpg', '256eedc26be5feda94dc6433951594d112216603.jpg', '7967d5dce48a58788f27821133fa70789bb10e8b.jpg', '6233ff6f9b52cd4eb67f364ac44d8cb36555c0f7.jpg'],
        'mediaURL': 'https://s3-us-west-2.amazonaws.com/avenuehq-listings/fvrebgv/000/262/418/',
        'size': {'low': 763, 'high': 763},
        'squareFootage': 0,
        'acres': 0,
        'title': '#4301 - 1289 Hornby Street',
        'position': {'lat': 49.2774773, 'lng': -123.1295852},
        'agent': 'Andy Hsu PREC*',
        'office': 'RE/MAX Crest Realty',
        'openHouses': 0,
        'openHouseBanners': None,
        'lolType': 'condo'}


class City(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.name


class State(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.name


class Ownership(models.Model):
    id = models.AutoField(primary_key=True)
    value = models.CharField(max_length=100, unique=True)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.value


class Media(models.Model):
    house = models.ForeignKey('House',on_delete=models.CASCADE,default=None)
    src = models.CharField(max_length=200)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.house.mediaURL+self.src


class Type(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,unique=True)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.name


class House(models.Model):
    id = models.IntegerField(primary_key=True)
    address = models.TextField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    ownership = models.ForeignKey(Ownership, on_delete=models.CASCADE,null=True)
    public_remarks = models.TextField(null=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    dateListed = models.DateTimeField(null=True)
    mediaURL = models.TextField(null=True)
    # Since in API's ADT, "size" field has min and max values which both are the same.
    # And "squareFootage" field is 0 for most of the objects.
    # In API "size" field has been used instead of square foot.
    # So we have ignored "squareFootage" field.
    # Since "acres" field is derived from "size" so we have ignored that too.
    size = models.IntegerField()
    title = models.CharField(max_length=200, null=True)
    office = models.CharField(max_length=200, null=True)
    lol_type = models.ForeignKey(Type, on_delete=models.CASCADE)

    def __str__(self):
        return 'R%i' % self.id

gopal/views.py
from django.shortcuts import render,HttpResponse
from gopal.models import *


def home(request):
    context = {}
    return render(request,'gopal/home.html',context)
    pass


def list(request):
    houses = House.objects.all()
    states = State.objects.all()
    cities = City.objects.all()
    empty = False

    if hasattr(request,'GET'):
        if len(houses)>0 and 'price_least' in request.GET.keys() and len(request.GET['price_least']):
            houses = houses.filter(price__gt=int(request.GET['price_least']))
        if len(houses)>0 and 'price_most' in request.GET.keys() and len(request.GET['price_most']):
            houses = houses.filter(price__lt=int(request.GET['price_most']))
        if len(houses)>0 and 'city' in request.GET.keys() and len(request.GET['city']):
            houses = houses.filter(city=City.objects.get(name=request.GET['city']))
        if len(houses)>0 and 'state' in request.GET.keys() and len(request.GET['state']):
            houses = houses.filter(state=State.objects.get(name=request.GET['state']))

    if len(houses) == 0: empty = True

    for house in houses:
        ans = house.media_set.all()
        if len(ans) > 0:
            house.img_src = ans[0]
        else:house.img_src = None
    context = {
        'count': len(houses),
        'houses': houses,
        'states': states,
        'cities': cities,
        'empty': empty
    }
    return render(request,'gopal/list.html',context)
    pass


def estimate(request):
    context = dict()
    context["states"] = [state.name for state in State.objects.all()]
    context["cities"] = [city.name for city in City.objects.all()]
    context['types'] = [type.name for type in Type.objects.all()]
    context['ownerships'] = [item.value for item in Ownership.objects.all()]

    if request.method=="POST":

        for key, value in request.POST.items():
            print(key,value)
            context[key] = value
        del context['csrfmiddlewaretoken']

        with open('houses_trained.pkl', 'rb') as f:
            import pickle
            regr = pickle.load(f)
            predicted = regr.predict([
                [int(context['bedrooms']), int(context['baths']), int(context['size']),
                Type.objects.get(name=context['type']).id, State.objects.get(name=context['state']).id,
                City.objects.get(name=context['city']).id, Ownership.objects.get(value=context['ownership']).id]])
            context['predicted_price'] = int(predicted[0])

    return render(request,'gopal/estimate.html',context)
    pass


def house_view(request,house_id):
    import requests
    r = requests.get('https://gopalsharma.ca/listing/R'+str(house_id))
    if r.status_code == 200:
        return HttpResponse(r.text)
    else:
        return HttpResponse("house with %d id details." % house_id)
    pass

gopal/templates/gopal/baseTemplate.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "gopal/css/main.css" %}" type="text/css">
        <title>
        {% block title %}
            Sajad Kh
        {% endblock %}
        </title>
    </head>
    <body>
        <div class="container">
            {% block body %}
                <h1>Hello world</h1>
            {% endblock %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block more-js %}{% endblock %}
    </body>
</html>

gopal/templates/gopal/estimate.html
{% extends 'gopal/baseTemplate.html' %}
{% block title %}
    Price estimating
{% endblock %}

{% block body %}
<div class="jumbotron mt-5">
    <h1 class="text-center pb-5 display-4"><b><strong>Estimate price</strong></b><b>!!</b></h1>
    <p class="lead">Here you can estimate your favorite hypothetical house price!!<br></p>
    <div id="alerts-container">
        {% if predicted_price %}
            {% if predicted_price > 0 %}
                <div class="alert alert-success text-center lead" role="alert">The estimated price is <b>{{ predicted_price }} $</b></div>
            {% else %}
                <div class="alert alert-warning text-center lead" role="alert">The estimated price is <b>{{ predicted_price }} $</b>.
                    The entered data doesn't make sense.</div>
            {% endif %}
        {% endif %}
    </div>

    <hr class="my-4">
    <form method="post" action="#">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="size">Size(by square foot)</label>
                <input name="size" type="number" class="form-control" id="size" placeholder="Enter size" value="{{ size }}">
            </div>
            <div class="form-group col-md-2">
                <label for="bed-rooms">Bed rooms count</label>
                <input name="bedrooms" type="number" class="form-control" id="bed-rooms" placeholder="Enter count" value="{{ bedrooms }}" >
            </div>
            <div class="form-group col-md-2">
                <label  for="bath-rooms">Bath rooms count</label>
                <input name="baths" type="number" class="form-control" id="bath-rooms" placeholder="Enter count" value="{{ baths }}">
            </div>
        </div>
        <div class="form-row mt-4">
            <div class="form-group col-md-3">
                <label for="state">State</label>
                <select name='state' id="state" class="form-control">
                    {% for item in states %}
                        {% if item == state %}
                            <option selected>{{ item }}</option>
                        {% else %}
                            <option>{{ item }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="city">City</label>
                <select name='city' id="city" class="form-control">
                    {% for item in cities %}
                        {% if item == city %}
                            <option selected>{{ item }}</option>
                        {% else %}
                            <option>{{ item }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="type">House type</label>
                <select name='type' id="type" class="form-control" >
                    {% for item in types %}
                        {% if item == type %}
                            <option selected>{{ item }}</option>
                        {% else %}
                            <option>{{ item }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="ownership">Ownership</label>
                <select name='ownership' id="ownership" class="form-control">
                    {% for item in ownerships %}
                        {% if item == ownership %}
                            <option selected>{{ item }}</option>
                        {% else %}
                            <option>{{ item }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <button type="button" onclick="validateAndSubmit()"  class="btn btn-success mt-4">Calculate</button>
    </form>

</div>
{% endblock %}

{% block more-js %}
    <script>
        function validateAndSubmit() {
            console.log("Itarim daii!")
            $('#alerts-container').empty()
            alertContainer = document.getElementById("alerts-container")
            size = document.getElementById('size')
            bedRooms = document.getElementById('bed-rooms')
            bathRooms = document.getElementById('bath-rooms')
            if (size.value =="") {
                alertContainer.innerHTML = alertContainer.innerHTML+
                    "<div class='alert alert-danger' role='alert'>\"Size\" field can not be empty!</div>"
                return
            }
            if (bedRooms.value == "") {
                alertContainer.innerHTML = alertContainer.innerHTML+
                    "<div class='alert alert-danger' role='alert'>\"Bed rooms count\" field can not be empty!</div>"
                return
            }
            if (bathRooms.value == "") {
                alertContainer.innerHTML = alertContainer.innerHTML+
                    "<div class='alert alert-danger' role='alert'>\"Bath rooms count\" field can not be empty!</div>"
                return
            }
            document.getElementsByTagName('form')[0].submit()
        }
    </script>
{% endblock %}

gopal/templates/gopal/home.html
{% extends 'gopal/baseTemplate.html' %}
{% block title %}
    Home
{% endblock %}

{% block body %}
<div class="jumbotron mt-5 ">
    <h1 class="display-4 text-center">Welcome</h1>
    <p class="lead mt-5">The purpose in this project is digging out raw data of selling houses from this site.
        Then insert them into our local database and visualize them into our django-base website.
        And finally we are going to implement a learner agent that estimates price of houses by their features.
        By the way this project is going to be developed only for fun and learning purpose. Thanks to dear
        <a href="https://github.com/jadijadi/">Jadi</a> for this idea.</p>

    <hr class="my-4">
    <p class="lead  text-center">
        <a class="btn btn-success" href="{% url "gopal:list" %}">See houses</a>
        <a class="btn btn-success" href="{% url "gopal:estimate" %}">Estimate price</a>
    </p>
    <hr class="mt-4">
    <p class="lead">Developed by <a  href="https://github.com/sajadkhosravani1"><b>Sajad Khosravani</b></a>.</p>
</div>
{% endblock %}

gopal/templates/gopal/list.html
{% extends 'gopal/baseTemplate.html' %}
{% load static %}
{% block title %}
    Houses
{% endblock %}



{% block body %}
    <form id="filter-form-container" class="form-inline" method="get" >
        <label for="select-state" class="text-light ml-2 mr-1">State</label>
        <select class="form-control" id="select-state" name="state">
            {% for state in states %}
                <option>{{ state.name }}</option>
            {% endfor %}
        </select>

        <label for="select-city" class="text-light ml-3 mr-1">City</label>
        <select class="form-control" id="select-city" name="city">
            {% for city in cities %}
                <option>{{ city.name }}</option>
            {% endfor %}
        </select>

        <label class="text-light ml-5 mr-2"><strong>Price:</strong></label>
        <label for="price-least" class="text-light ml-2 mr-1">From</label>
        <input class="form-control price-input" type="number" name="price_least" id="price-least">
        <label for="price-most" class="text-light ml-2 mr-1">To</label>
        <input class="form-control price-input" type="number" name="price_most" id="price-most">
        <button type="submit" class="btn btn-success ml-auto mr-3"> Reload </button>
    </form>
    <div id="empty"></div>
    <div class="d-flex flex-wrap">
    {% if not empty %}
        {% for house in houses %}
            <a href="{% url 'gopal:house_view' house_id=house.id%}" class="card-link">
            <div class="card list-card">
            <div class="house-image" style="background-image:url('{% if house.img_src %}{{ house.img_src }}{% else %}{% static "gopal/image/house.png"  %}{% endif%}');"></div>

                <div class="card-body">
                    <h5 class="card-title">{{ house.price }}$</h5>
                    <p class="card-text">{{house.title}}</p>
                </div>

                <ul class="list-group list-group-flush p-4" >
                    <li class="list-group-item">{{ house.address }}</li>
                    <li class="list-group-item">{{ house.city}},{{ house.state }}</li>
                    <li class="list-group-item">{{ house.office}}</li>
                </ul>
            </div>
            </a>
        {% endfor %}
    {% else %}
        <div class="mx-auto">
            <img src="{% static "gopal/image/notfound.png" %}" class="mx-auto d-block"/>
            <h2 class="d-block mx-auto text-center">Nothing found!</h2>
        </div>

    {% endif %}
    </div>
{% endblock %}

{% block more-js %}
    <script>
        window.onscroll = function() {myFunction()};

        var navbar = document.getElementById("filter-form-container");
        var empty = document.getElementById("empty")
        var sticky = navbar.offsetTop;

        function myFunction() {
            if (window.pageYOffset >= sticky) {
                navbar.classList.add("sticky")
                empty.classList.add("py-5")
            } else {
                navbar.classList.remove("sticky");
                empty.classList.remove("py-5")
            }
        }
    </script>
{% endblock %}